### ISSUE TITLE
3.1.0 community not working with ACS Community 6.1.2-ga

### ISSUE THREAD

**Issue by igorbga** [Alfresco/googledrive#58]
A document can be created and edited in Google Drive, you can also cancel de edition, but when you try to save the document back to Alfresco by clicking "Check in Google Doc" it fails.

It seems to try for some time and then share rises a timeout error. 
I have tried with a manual install an also with a dockerised installation run in Alfresco SDK 4.0.

In the log, apart from the Share request timeout, in the platform log I can see some errors related to canned queries:

> 
>  2019-05-14 11:55:21,295  ERROR [web.scripts.RepositoryContainer] [http-nio-8080-exec-6] Server error (04140060)
> acme-main-acs_1      |  org.springframework.extensions.webscripts.WebScriptException: 04140046 04140059 Failed to execute query: 
> acme-main-acs_1      |    Namespace: alfresco.node
> acme-main-acs_1      |    queryName: select_GetChildrenCannedQueryWithProps
> acme-main-acs_1      |    Parameter: org.alfresco.repo.node.getchildren.FilterSortNodeEntity@414688f0
> acme-main-acs_1      |    Offset:    0
> acme-main-acs_1      |    Limit:     2147483647
> acme-main-acs_1      | 	at org.alfresco.integrations.google.docs.webscripts.SaveContent.executeImpl(SaveContent.java:317)
> acme-main-acs_1      | 	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
> 

But does appear after the timeout so I don't know if this is the real issue or is just the consecuence of a previous timeout.

**Comment by igorbga** [comment]
Sorry, noticed in the README that issues should be reported in Alfresco's JIRA.

**Comment by igorbga** [comment]
https://issues.alfresco.com/jira/browse/ALF-22084

**Comment by montgolfiere** [comment]
@igorbga Thanks
